### ISSUE TITLE
Design testing

### ISSUE THREAD

**Issue by mrgsts** [kuon/pcb-ucurrent#1]
Hello, have you been able to produced the PCB and proceeded to test the design?

**Comment by kuon** [comment]
Hi, I modified the design quite a bit. I pushed my latest version to github. I built it and it works but I was working on something else and I didn't run many tests (noise measurement, response time...).

**Comment by mrgsts** [comment]
Excelent work, i will send to pcb fab after make some adjustements to footprints :thumbsup:
 
> Hi, I modified the design quite a bit. I pushed my latest version to github. I built it and it works but I was working on something else and I didn't run many tests (noise measurement, response time...).

**Comment by kuon** [comment]
The PCB has this layout because of the case I used. There are no other technical reason.
